### ISSUE TITLE
more info in hover-over-windows

### ISSUE THREAD

**Issue by timlevine** [UCL/HHyeast-server#28]
Hi! 
When I hover the mouse over a hit (e.g. http://hhyeast.ukwest.cloudapp.azure.com:5000/LAS17/yeast) it would be great if the window that opens with "Match no." and "Description:" has

line 1: "Query" then the Query HMM values
line 2: "Hit:" [name - as already coded] then in brackets Template HMM values

**Comment by ilectra** [comment]
From @timlevine : (please put comments in the appropriate issues/Pull Requests! It's getting very confusing otherwise...)

I've been looking at the pages (e.g. http://hhyeast.ukwest.cloudapp.azure.com:5000/DCK1) I think that the presentaiton should be the name of the hit possibly with the %, but possibly without.

Also it would be good if the hover-over display stated where the match is in the target (limits of residues)

the changes to the more detailed pages (such as http://hhyeast.ukwest.cloudapp.azure.com:5000/DCK1/pdb) are excellent.

**Comment by ilectra** [comment]
@timlevine by "presentation", you mean this?
![summarypage_9jan18](https://user-images.githubusercontent.com/22891967/34725982-923c1c64-f54a-11e7-89a2-8ad76ba650d8.png)

**Comment by timlevine** [comment]
Yes - thanks for adding in the target names. Could this have the target range too? that could appear at the end of line 2 (in square or curly brackets) rather than on a new line.
Tim

**Comment by ilectra** [comment]
Do you mean the Query or the Template limits?

**Comment by timlevine** [comment]
template
