### ISSUE TITLE
Filter out short hits

### ISSUE THREAD

**Issue by ilectra** [UCL/HHyeast-server#9]
Filter out hits shorter than 30 residues (make threshold adjustable, so we could change our minds later), so they're not displayed or contribute to clustering.

**Comment by timlevine** [comment]
we decided on 30 to begin with

**Comment by timlevine** [comment]
See comments on how to parse database (in HHprY thread):
if protein has no hits at all >= 30 cols, it would be good to include hits 20-29 cols

re ACTION 2 from that long email (17 OCT): this said
"– include only alignments with 30 or more columns.
– make three separate files with a maximum of 500 (or 1000?) alignments for each of the three databases: PFAM, yeast and PDB. Could the searches be carried out separately, so that in future we could re-do one set without changing the others, or change the databases tested. This deals with #3 (YNL212W), as the top PH-like hit is only #138th Pfam hit (>500th hit in other 2 databases)."

If we are going back to including all hits >=20 columns, then will need to report 750 hits for each of the 3 databases so that in cases like YNL212W the minority and slightly weaker hits to one region are not completely buried under the vast majority of stronger hits to a different region

**Comment by ilectra** [comment]
Ignoring everything with prob>99%:
- if there are any hits with >=30 cols, ignore anything with <30cols
- if there are no hits with >=30 cols, include stuff with 20-30 cols.

**Comment by ilectra** [comment]
For any processing (clustering, etc....) ignore anything with prob>99%, cause it's already known. Just display it on the plot, but don't take it into account.
